---
title: "rxode2"
author: "Yugang"
format: html
editor: visual
---

```{r}
1 + 1
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).\

```{r}
mod1 <- function() {
  ini({
    # central 
    KA=2.94E-01
    CL=1.86E+01
    V2=4.02E+01
    # peripheral
    Q=1.05E+01
    V3=2.97E+02
    # effects
    Kin=1
    Kout=1
    EC50=200 
  })
  model({
    C2 <- centr/V2
    C3 <- peri/V3
    d/dt(depot) <- -KA*depot
    d/dt(centr) <- KA*depot - CL*C2 - Q*C2 + Q*C3
    d/dt(peri)  <- Q*C2 - Q*C3
    eff(0) <- 1
    d/dt(eff)   <- Kin - Kout*(1-C2/(EC50+C2))*eff
  })
}

model  = rxode2(mod1)
model
```

```{r}
ev  <- et(amountUnits="mg", timeUnits="hour") %>%
  et(amt=10000, addl=9,ii=12,cmt="depot") %>%
  et(time=120, amt=2000, addl=4, ii=14, cmt="depot") %>%
  et(0:240) # Add sampling 

ev
```

```{r}
library(rxode2)

set.seed(32)
rxSetSeed(32)

mod <- function() {
  ini({
    KA <- 2.94E-01
    TCl <- 1.86E+01
    # between subject variability
    eta.Cl ~ 0.4^2
    V2 <- 4.02E+01
    Q <- 1.05E+01
    V3 <- 2.97E+02
    Kin <- 1
    Kout <- 1
    EC50 <- 200
  })
  model({
    C2 <- centr/V2
    C3 <- peri/V3
    CL <-  TCl*exp(eta.Cl) ## This is coded as a variable in the model
    d/dt(depot) <- -KA*depot
    d/dt(centr) <- KA*depot - CL*C2 - Q*C2 + Q*C3
    d/dt(peri)  <-                    Q*C2 - Q*C3
    d/dt(eff)   <- Kin - Kout*(1-C2/(EC50+C2))*eff
    eff(0) <- 1
  })
}

ev <- et(amountUnits="mg", timeUnits="hours") %>%
  et(amt=10000, cmt="centr") %>%
    et(0,48, length.out=100)


sim  <- rxSolve(mod, ev, nSub=100)

conf <- confint(sim, "C2", level=0.95)

p <- plot(conf,ylab="Central Concentration", log="y")
print(p)

class(p)

```

```{r}
library(tidyverse)
sim %>% 
    group_by(time) %>% 
    summarise(
        median = median(C2),
        P05 = quantile(C2,0.05),
        P95 = quantile(C2,0.95),
    ) %>% ungroup() %>% 
    ggplot(aes(x=time))+
    geom_line(aes(x=time, y=median))+
    geom_ribbon(aes(x=time, ymin=P05, ymax=P95), alpha=0.1)+
    scale_y_log10()
        
```
