---
title: "rxode2_chapter5"
author: "Yugang"
format: html
editor: visual
execute: 
  warning: false
  echo: true
---

## Getting Started

```{r}
rm(list = ls())
library(rxode2)
library(tidyverse)
library(ggthemes)

sessionInfo()
```

### Set initial values and build up the model

```{r}
mod1 <- function() {
  ini({
    # central 
    KA=2.94E-01
    CL=1.86E+01
    V2=4.02E+01
    # peripheral
    Q=1.05E+01
    V3=2.97E+02
    # effects
    Kin=1
    Kout=1
    EC50=200 
  })
  model({
    C2 <- centr/V2
    C3 <- peri/V3
    d/dt(depot) <- -KA*depot
    d/dt(centr) <- KA*depot - CL*C2 - Q*C2 + Q*C3
    d/dt(peri)  <- Q*C2 - Q*C3
    
    #condition of the ODE
    eff(0) <- 1
    d/dt(eff)   <- Kin - Kout*(1-C2/(EC50+C2))*eff
  })
}
```

### Compile the model

```{r}
mod1 <- rxode2(mod1)
mod1

summary(mod1$simulationModel)
```

### Add events

```{r}
ev  <- et(amountUnits="mg", timeUnits="hours") %>%
  et(amt=10000, addl=9,ii=12,cmt="depot") %>%
  et(time=120, amt=2000, addl=4, ii=14, cmt="depot") %>%
  et(0:240) # Add sampling 

head(ev,10)
```

### Solve and plot

```{r}
mod1 %>% rxSolve(ev) %>% 
    plot(x,C2) + ylab("Central Concentration")
mod1 %>% rxSolve(ev) %>% 
    plot(x,eff)  + ylab("Effect") +xlab("Time[h]")
```

However, the x-axis title is not automated with \[h\], add it manually.
